import { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Button, Card, Header, Screen } from '@/src/components/UI';
import { StaffMember, useAdminAuth } from '@/src/context/AdminAuthContext';
import { supabase } from '@/src/lib/supabase';
import { colors } from '@/src/theme';

export default function AdminStaff() {
  const auth = useAdminAuth(); const [members,setMembers]=useState<StaffMember[]>([]); const[email,setEmail]=useState('');const[name,setName]=useState('');const[role,setRole]=useState<'admin'|'staff'>('staff');const[busy,setBusy]=useState(false);const[error,setError]=useState('');
  const load=useCallback(async()=>{if(!supabase)return;const result=await supabase.from('cafe_staff').select('*').order('email');if(result.error)setError(result.error.message);else setMembers(result.data.map(row=>({userId:row.user_id,email:row.email,displayName:row.display_name,role:row.role})));},[]);
  useEffect(()=>{void load();},[load]);
  const add=async()=>{if(!supabase)return;setBusy(true);setError('');const result=await supabase.rpc('authorize_cafe_staff',{staff_email:email.trim().toLowerCase(),staff_display_name:name.trim(),staff_role:role});if(result.error)setError(result.error.message);else{setEmail('');setName('');await load();}setBusy(false);};
  const remove=async(member:StaffMember)=>{if(!supabase)return;setBusy(true);const result=await supabase.from('cafe_staff').delete().eq('email',member.email);if(result.error)setError(result.error.message);else await load();setBusy(false);};
  return <Screen><Header title="Staff Access"/><Text style={s.help}>Authorize an existing Supabase Auth email here. Public account creation is disabled; admins manage who can use the cafe dashboard.</Text>{auth.staff?.role==='admin'&&<Card><Text style={s.label}>Staff email</Text><TextInput style={s.input} value={email} onChangeText={setEmail} autoCapitalize="none" keyboardType="email-address" placeholder="staff@cafe.co.nz"/><Text style={s.label}>Display name</Text><TextInput style={s.input} value={name} onChangeText={setName} placeholder="e.g. Sam"/><View style={s.roles}>{(['staff','admin'] as const).map(value=><Pressable key={value} style={[s.role,role===value&&s.roleActive]} onPress={()=>setRole(value)}><Text style={[s.roleText,role===value&&{color:colors.white}]}>{value==='admin'?'Admin':'Staff'}</Text></Pressable>)}</View><Button label={busy?'Saving…':'Add authorized staff'} disabled={busy||!email.includes('@')} onPress={()=>void add()}/></Card>}{!!error&&<Text style={s.error}>{error}</Text>}<Text style={s.heading}>Authorized people</Text>{members.map(member=><Card key={member.email} style={s.member}><View style={{flex:1}}><Text style={s.name}>{member.displayName||member.email.split('@')[0]}</Text><Text style={s.email}>{member.email} · {member.role.toUpperCase()}</Text></View>{auth.staff?.role==='admin'&&member.email!==auth.staff.email&&<Pressable onPress={()=>void remove(member)} disabled={busy}><Text style={s.remove}>Remove</Text></Pressable>}</Card>)}</Screen>;
}
const s=StyleSheet.create({help:{color:colors.muted,lineHeight:20,marginBottom:14},label:{color:colors.ink,fontWeight:'700',marginBottom:7,marginTop:8},input:{height:50,borderWidth:1,borderColor:colors.line,borderRadius:13,paddingHorizontal:13,marginBottom:7},roles:{flexDirection:'row',gap:8,marginVertical:10},role:{flex:1,alignItems:'center',padding:11,borderRadius:12,backgroundColor:colors.cream},roleActive:{backgroundColor:colors.espresso},roleText:{fontWeight:'800',color:colors.espresso},error:{color:colors.danger,marginVertical:10},heading:{color:colors.ink,fontSize:19,fontWeight:'800',marginVertical:15},member:{flexDirection:'row',alignItems:'center',marginBottom:9},name:{fontWeight:'800',color:colors.ink},email:{color:colors.muted,fontSize:12,marginTop:4},remove:{color:colors.danger,fontWeight:'800'}});
