import { router } from 'expo-router';
import { useState } from 'react';
import { Alert, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Button, Card, Header, Screen } from '@/src/components/UI';
import { useTables } from '@/src/context/TableContext';
import { colors } from '@/src/theme';
export default function AdminTables() { const { tables, loading, error, addTable, updateTable, removeTable } = useTables(); const [code, setCode] = useState(''); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const [message, setMessage] = useState(''); const add = async () => { setBusy(true); setMessage(''); try { await addTable(code, name); setCode(''); setName(''); } catch (e) { setMessage(e instanceof Error ? e.message : 'Could not add table.'); } finally { setBusy(false); } }; return <Screen><Header title="Table Management" /><Text style={styles.help}>Create a table, then open its printable QR card.</Text><Card style={styles.form}><Text style={styles.label}>QR code / number</Text><TextInput style={styles.input} value={code} onChangeText={setCode} placeholder="5" placeholderTextColor={colors.muted} /><Text style={styles.label}>Display name</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Table 5" placeholderTextColor={colors.muted} /><Button label={busy ? 'Adding…' : 'Add table'} disabled={busy || !code.trim() || !name.trim()} onPress={add} /></Card>{!!message && <Text style={styles.error}>{message}</Text>}{!!error && <Text style={styles.error}>{error}</Text>}<Text style={styles.heading}>{loading ? 'Loading…' : `${tables.length} tables`}</Text>{tables.map(table => <Card key={table.id} style={styles.table}><View style={{ flex: 1 }}><Text style={styles.name}>{table.name}</Text><Text style={styles.link}>/?table={table.code}</Text></View><Pressable style={styles.icon} onPress={() => void updateTable(table.id, { active: !table.active })}><Ionicons name={table.active ? 'checkmark-circle' : 'close-circle-outline'} size={23} color={table.active ? colors.green : colors.muted} /></Pressable><Pressable style={styles.icon} onPress={() => router.push({ pathname: '/admin-table-qr', params: { id: table.id } })}><Ionicons name="qr-code-outline" size={22} color={colors.espresso} /></Pressable><Pressable style={styles.icon} onPress={() => Alert.alert('Remove table?', table.name, [{ text: 'Cancel' }, { text: 'Remove', style: 'destructive', onPress: () => void removeTable(table.id) }])}><Ionicons name="trash-outline" size={21} color={colors.danger} /></Pressable></Card>)}</Screen>; }
const styles = StyleSheet.create({ help: { color: colors.muted, marginBottom: 14 }, form: { marginBottom: 16 }, label: { color: colors.ink, fontWeight: '700', marginBottom: 7 }, input: { height: 50, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.line, borderRadius: 14, paddingHorizontal: 14, marginBottom: 13, color: colors.ink }, heading: { color: colors.ink, fontSize: 19, fontWeight: '800', marginVertical: 12 }, table: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 }, name: { color: colors.ink, fontWeight: '800', fontSize: 16 }, link: { color: colors.muted, marginTop: 4, fontSize: 12 }, icon: { padding: 9 }, error: { color: colors.danger, marginBottom: 10 } });
