import { router } from 'expo-router';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { Button, Card, Header, Screen } from '@/src/components/UI';
import { useLoyalty } from '@/src/context/LoyaltyContext';
import { money } from '@/src/data/products';
import { colors } from '@/src/theme';

export default function RewardsScreen(){const{balance,settings,promos}=useLoyalty();const active=promos.filter(p=>p.enabled&&(!p.expiresAt||new Date(p.expiresAt)>=new Date()));const progress=Math.min(100,balance.coffeeStamps/settings.coffeeGoal*100);return <Screen><Header title="Rewards & Offers"/><View style={s.hero}><Text style={s.eyebrow}>YOUR LOYALTY BALANCE</Text><Text style={s.points}>{balance.points} points</Text><Text style={s.help}>{settings.pointsPerDollar} point{settings.pointsPerDollar===1?'':'s'} for every $1 spent</Text></View><Card style={s.rewardCard}><View style={s.rewardTop}><View style={s.icon}><Ionicons name="cafe" size={23} color={colors.green}/></View><View style={{flex:1}}><Text style={s.title}>Buy {settings.coffeeGoal}, get 1 free</Text><Text style={s.muted}>{balance.coffeeStamps} of {settings.coffeeGoal} coffee stamps</Text></View></View><View style={s.track}><View style={[s.fill,{width:`${progress}%`}]} /></View><Text style={s.progress}>{balance.freeCoffees>0?`🎉 ${balance.freeCoffees} free coffee reward${balance.freeCoffees===1?' is':'s are'} available now.`:`Only ${Math.max(0,settings.coffeeGoal-balance.coffeeStamps)} more coffee${settings.coffeeGoal-balance.coffeeStamps===1?'':'s'} until your next free one.`}</Text>{balance.freeCoffees>0&&<Text style={s.applyHelp}>Add a coffee to your cart, then tap “Use reward” in cart or checkout.</Text>}</Card><View style={s.headingRow}><Text style={s.heading}>Current offers</Text><Ionicons name="pricetags-outline" size={20} color={colors.caramel}/></View>{active.length?active.map(promo=><Card key={promo.id} style={s.offer}><View style={s.offerBadge}><Text style={s.code}>{promo.code}</Text></View><Text style={s.offerTitle}>{promo.description||'Cafe promotion'}</Text><Text style={s.offerText}>{promo.discountType==='percent'?`${promo.discountValue}% off`:`${money(promo.discountValue)} off`}{promo.minimumSpend?` · Minimum spend ${money(promo.minimumSpend)}`:''}</Text>{promo.expiresAt&&<Text style={s.expiry}>Expires {new Date(promo.expiresAt).toLocaleDateString()}</Text>}</Card>):<Card><Text style={s.muted}>No promo codes are active right now. Your loyalty rewards are still earning.</Text></Card>}<View style={{flex:1,minHeight:24}}/><Button label="Browse the menu" icon="cafe-outline" onPress={()=>router.replace('/')}/></Screen>}
const s=StyleSheet.create({hero:{backgroundColor:'#335943',borderRadius:23,padding:20,marginBottom:14},eyebrow:{color:'#BDD2C1',fontWeight:'800',letterSpacing:1.2,fontSize:10},points:{color:colors.white,fontSize:34,fontWeight:'900',marginTop:6},help:{color:'#D7E5DA',marginTop:4},rewardCard:{marginBottom:18},rewardTop:{flexDirection:'row',alignItems:'center',gap:11},icon:{width:47,height:47,borderRadius:15,backgroundColor:colors.greenSoft,alignItems:'center',justifyContent:'center'},title:{fontWeight:'900',color:colors.ink,fontSize:17},muted:{color:colors.muted,marginTop:4,lineHeight:19},track:{height:10,backgroundColor:'#DDE8DF',borderRadius:6,overflow:'hidden',marginTop:15},fill:{height:'100%',backgroundColor:colors.green,borderRadius:6},progress:{color:colors.green,fontWeight:'800',marginTop:10},applyHelp:{color:colors.muted,fontSize:11,marginTop:6,lineHeight:16},headingRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:10},heading:{fontSize:20,fontWeight:'900',color:colors.ink},offer:{marginBottom:10},offerBadge:{alignSelf:'flex-start',backgroundColor:colors.espresso,borderRadius:9,paddingHorizontal:10,paddingVertical:6},code:{color:colors.white,fontWeight:'900',letterSpacing:1},offerTitle:{fontWeight:'800',color:colors.ink,fontSize:16,marginTop:10},offerText:{color:colors.green,fontWeight:'800',marginTop:5},expiry:{color:colors.muted,fontSize:11,marginTop:5}});
