create table if not exists public.orders (
  id text primary key,
  customer_name text not null check (char_length(customer_name) between 1 and 100),
  phone text not null check (char_length(phone) between 1 and 40),
  pickup_time text not null,
  total_cents integer not null check (total_cents >= 0),
  status text not null default 'Incoming' check (status in ('Incoming', 'Preparing', 'Ready', 'Collected')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id) on delete cascade,
  product_id text not null,
  product_name text not null,
  unit_price_cents integer not null check (unit_price_cents >= 0),
  quantity integer not null check (quantity > 0),
  notes text
);

create index if not exists orders_status_created_at_idx on public.orders (status, created_at desc);
create index if not exists order_items_order_id_idx on public.order_items (order_id);

create or replace function public.set_orders_updated_at()
returns trigger language plpgsql set search_path = '' as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists orders_set_updated_at on public.orders;
create trigger orders_set_updated_at before update on public.orders
for each row execute function public.set_orders_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
revoke all on table public.orders from anon, authenticated;
revoke all on table public.order_items from anon, authenticated;
grant select, insert on table public.orders to anon, authenticated;
grant update (status) on table public.orders to anon, authenticated;
grant select, insert on table public.order_items to anon, authenticated;
grant usage, select on sequence public.order_items_id_seq to anon, authenticated;

drop policy if exists "Public can read cafe orders" on public.orders;
create policy "Public can read cafe orders" on public.orders for select to anon, authenticated using (true);
drop policy if exists "Customers can place cafe orders" on public.orders;
create policy "Customers can place cafe orders" on public.orders for insert to anon, authenticated with check (status = 'Incoming');
drop policy if exists "Cafe admin can update order status" on public.orders;
create policy "Cafe admin can update order status" on public.orders for update to anon, authenticated using (true) with check (status in ('Incoming', 'Preparing', 'Ready', 'Collected'));
drop policy if exists "Public can read cafe order items" on public.order_items;
create policy "Public can read cafe order items" on public.order_items for select to anon, authenticated using (true);
drop policy if exists "Customers can add cafe order items" on public.order_items;
create policy "Customers can add cafe order items" on public.order_items for insert to anon, authenticated with check (true);

do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders') then
    alter publication supabase_realtime add table public.orders;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'order_items') then
    alter publication supabase_realtime add table public.order_items;
  end if;
end $$;
