-- Idempotent Loyalty & Promotions migration. No tables or existing data are dropped.
create table if not exists public.loyalty_settings(id integer primary key default 1 check(id=1),points_per_dollar numeric not null default 1 check(points_per_dollar>=0),coffee_goal integer not null default 4 check(coffee_goal>0),free_coffee_max_cents integer not null default 1000 check(free_coffee_max_cents>=0),enabled boolean not null default true,updated_at timestamptz not null default now());
insert into public.loyalty_settings(id)values(1)on conflict do nothing;
create table if not exists public.promo_codes(id uuid primary key default gen_random_uuid(),code text not null unique,description text not null default'',discount_type text not null check(discount_type in('percent','fixed')),discount_value numeric not null check(discount_value>=0),minimum_spend_cents integer not null default 0 check(minimum_spend_cents>=0),expires_at timestamptz,enabled boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table if not exists public.customer_loyalty(customer_key text primary key,points integer not null default 0 check(points>=0),coffee_stamps integer not null default 0 check(coffee_stamps>=0),free_coffees integer not null default 0 check(free_coffees>=0),updated_at timestamptz not null default now());
alter table public.orders add column if not exists customer_key text;
alter table public.orders add column if not exists subtotal_cents integer;
alter table public.orders add column if not exists discount_cents integer not null default 0;
alter table public.orders add column if not exists promo_code text;
alter table public.orders add column if not exists free_coffee_discount_cents integer not null default 0;
alter table public.orders add column if not exists points_earned integer not null default 0;
alter table public.orders add column if not exists points_redeemed integer not null default 0;
update public.orders set subtotal_cents=total_cents where subtotal_cents is null;
alter table public.orders alter column subtotal_cents set not null;
alter table public.loyalty_settings enable row level security;alter table public.promo_codes enable row level security;alter table public.customer_loyalty enable row level security;
grant select,update on public.loyalty_settings to anon,authenticated;grant select,insert,update on public.promo_codes to anon,authenticated;grant select,insert,update on public.customer_loyalty to anon,authenticated;
do $$ begin
if not exists(select 1 from pg_policies where schemaname='public' and tablename='loyalty_settings' and policyname='Public loyalty settings')then create policy "Public loyalty settings" on public.loyalty_settings for all to anon,authenticated using(true)with check(true);end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='promo_codes' and policyname='Public promo management')then create policy "Public promo management" on public.promo_codes for all to anon,authenticated using(true)with check(true);end if;
if not exists(select 1 from pg_policies where schemaname='public' and tablename='customer_loyalty' and policyname='Customer loyalty access')then create policy "Customer loyalty access" on public.customer_loyalty for all to anon,authenticated using(true)with check(true);end if;end $$;
create or replace function public.finalize_cafe_rewards(p_order_id text,p_customer_key text,p_promo_code text,p_items jsonb)returns void language plpgsql security definer set search_path='' as $$
declare cfg public.loyalty_settings%rowtype;loyalty public.customer_loyalty%rowtype;promo public.promo_codes%rowtype;subtotal integer;promo_discount integer:=0;free_discount integer:=0;final_total integer;earned integer:=0;coffee_count integer:=0;new_stamps integer;new_free integer;redeemed integer:=0;
begin select * into cfg from public.loyalty_settings where id=1;insert into public.customer_loyalty(customer_key)values(p_customer_key)on conflict do nothing;select * into loyalty from public.customer_loyalty where customer_key=p_customer_key for update;select coalesce(sum((item->>'unit_price_cents')::integer*(item->>'quantity')::integer),0),coalesce(sum(case when coalesce((item->>'is_coffee')::boolean,false)then(item->>'quantity')::integer else 0 end),0)into subtotal,coffee_count from jsonb_array_elements(p_items)item;
if p_promo_code is not null then select * into promo from public.promo_codes where upper(code)=upper(trim(p_promo_code))and enabled=true and subtotal>=minimum_spend_cents and(expires_at is null or expires_at>=now());if found then if promo.discount_type='percent'then promo_discount:=floor(subtotal*promo.discount_value/100);else promo_discount:=promo.discount_value::integer;end if;end if;end if;
if cfg.enabled and loyalty.free_coffees>0 and coffee_count>0 then select least(cfg.free_coffee_max_cents,min((item->>'unit_price_cents')::integer))into free_discount from jsonb_array_elements(p_items)item where coalesce((item->>'is_coffee')::boolean,false);redeemed:=1;end if;final_total:=greatest(0,subtotal-promo_discount-free_discount);if cfg.enabled then earned:=floor((final_total/100.0)*cfg.points_per_dollar);new_stamps:=loyalty.coffee_stamps+coffee_count;new_free:=loyalty.free_coffees-redeemed+(new_stamps/cfg.coffee_goal);new_stamps:=mod(new_stamps,cfg.coffee_goal);update public.customer_loyalty set points=points+earned,coffee_stamps=new_stamps,free_coffees=new_free,updated_at=now()where customer_key=p_customer_key;end if;update public.orders set subtotal_cents=subtotal,discount_cents=least(subtotal,promo_discount+free_discount),promo_code=case when promo.id is null then null else promo.code end,free_coffee_discount_cents=free_discount,points_earned=earned,points_redeemed=redeemed,total_cents=final_total where id=p_order_id;end $$;
create or replace function public.place_cafe_order(p_id text,p_customer_name text,p_phone text,p_pickup_time text,p_pickup_slot text,p_items jsonb,p_customer_key text,p_promo_code text default null)returns void language plpgsql security definer set search_path='' as $$ declare slot_limit integer;slot_count integer;begin if p_pickup_slot is null or p_pickup_slot=''then raise exception'Please select a pickup time';end if;perform pg_advisory_xact_lock(hashtext(p_pickup_slot));select max_orders_per_slot into slot_limit from public.cafe_settings where id=1;select count(*)into slot_count from public.orders where pickup_slot=p_pickup_slot;if slot_count>=slot_limit then raise exception'This pickup time has just filled up. Please choose another time.';end if;insert into public.orders(id,customer_name,phone,pickup_time,pickup_slot,total_cents,subtotal_cents,status,order_type,customer_key)values(p_id,p_customer_name,p_phone,p_pickup_time,p_pickup_slot,0,0,'Incoming','pickup',p_customer_key);perform public.insert_cafe_order_items(p_id,p_items);perform public.finalize_cafe_rewards(p_id,p_customer_key,p_promo_code,p_items);end $$;
create or replace function public.place_table_order(p_id text,p_table_id uuid,p_order_notes text,p_items jsonb,p_customer_key text,p_promo_code text default null)returns void language plpgsql security definer set search_path='' as $$ declare selected_table public.cafe_tables%rowtype;begin select * into selected_table from public.cafe_tables where id=p_table_id and active=true;if not found then raise exception'This table is not available';end if;insert into public.orders(id,customer_name,phone,pickup_time,pickup_slot,total_cents,subtotal_cents,status,order_type,table_id,table_code,table_name,order_notes,customer_key)values(p_id,selected_table.display_name,'Table order','Table service',null,0,0,'Incoming','table',selected_table.id,selected_table.code,selected_table.display_name,nullif(trim(p_order_notes),''),p_customer_key);perform public.insert_cafe_order_items(p_id,p_items);perform public.finalize_cafe_rewards(p_id,p_customer_key,p_promo_code,p_items);end $$;
grant execute on function public.place_cafe_order(text,text,text,text,text,jsonb,text,text)to anon,authenticated;grant execute on function public.place_table_order(text,uuid,text,jsonb,text,text)to anon,authenticated;
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename='loyalty_settings')then alter publication supabase_realtime add table public.loyalty_settings;end if;if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename='promo_codes')then alter publication supabase_realtime add table public.promo_codes;end if;if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime'and schemaname='public'and tablename='customer_loyalty')then alter publication supabase_realtime add table public.customer_loyalty;end if;end $$;
